FROM openjdk:11 AS build
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y maven
RUN mvn clean package -DskipTests

FROM openjdk:11-jdk-slim
COPY --from=build /app/target/examserver.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app.jar"]


